obj/DbObject.o: src/DbObject.cpp include/tincan/DbObject.h \
  include/tincan/PreparedStatement.h include/tincan/exceptions.h \
  include/tincan/declarations.h include/tincan/disable_copy.h \
  include/tincan/Field.h include/tincan/release_assert.h
obj/main.o: test/src/main.cpp include/tincan/tincan.h include/tincan/Field.h \
  include/tincan/Metainfo.h include/tincan/disable_copy.h \
  include/tincan/DbObject.h include/tincan/PreparedStatement.h \
  include/tincan/exceptions.h include/tincan/declarations.h
