obj/DbException.o: src/DbException.cpp include/tincan/DbException.h \
  include/tincan/db/PreparedStatement.h \
  include/tincan/db/../declarations.h
test/obj/main.o: test/src/main.cpp test/testcpp/include/testcpp/testcpp.h \
  test/testcpp/include/utilcpp/declarations.h \
  test/testcpp/include/utilcpp/scoped_ptr.h \
  test/testcpp/include/utilcpp/release_assert.h \
  test/testcpp/include/utilcpp/disable_copy.h \
  test/testcpp/include/testcpp/assert_impl.h include/tincan/tincan.h \
  include/tincan/Field.h include/tincan/Metainfo.h \
  include/tincan/disable_copy.h include/tincan/DbObject.h \
  include/tincan/db/FieldVisitors.h include/tincan/db/DbFieldType.h \
  include/tincan/db/../release_assert.h \
  include/tincan/db/PreparedStatement.h \
  include/tincan/db/../declarations.h
